### ISSUE TITLE
form-check in bs dropdown doesnt show check icon (materia theme)

### ISSUE THREAD

**Issue by mredl** [thomaspark/bootswatch#797] opened 2018-02-27 18:15 UTC
If you put some checkboxes (form-check) within a bs dropdown, it doesnt show the check icons
![image](https://user-images.githubusercontent.com/17241159/36746392-8344f61c-1bf2-11e8-9a48-a8fc3347c2af.png)

**Comment by thomaspark** [comment] 2018-02-28 01:01
@mredl, thanks for the bug report. Can you post a code sample on JSFiddle or JSBin?

**Comment by mredl** [comment] 2018-02-28 19:42
i have created an jsfiddle and there it works which makes me a little bit confusing...
https://jsfiddle.net/1685svjx/17/
sorry for this wrong alarm

**Comment by thomaspark** [comment] 2018-02-28 21:34
Thanks for the fiddle. It might be a Chrome rendering bug interacting between `column-count` greater than 1 and `:after` pseudo elements. It seems to render ok in Firefox and Safari. Can you check those browsers? It also seems ok in Chrome when the `column-count` of `.card-columns` is set to 1.

**Comment by mredl** [comment] 2018-03-01 10:29
Yes it looks like a browser bug, but the styling looks different in IE.
![image](https://user-images.githubusercontent.com/17241159/36839601-ceb0d70a-1d42-11e8-8347-75cc21539f8d.png)
There is no black background.
I have overriden the fiddle and changed the column count to 1, but it has not changed anything. here is the fiddle: https://jsfiddle.net/1685svjx/27/

**Comment by thomaspark** [comment] 2018-03-01 19:28
Thanks, your new fiddle is working for me in Chrome. In IE and some other browsers, it may not be possible to have the stylized checkboxes, so they have the default checkbox as fallback.

Looks like things are working as intended aside from the Chrome bug, and since that can't be fixed within Bootswatch, I'll close this issue.

**Closed by thomaspark** 2018-03-01 19:28 UTC
